import Head from "next/head";
import BackgroundDisplay from "@/components/BackgroundDisplay/BackgroundDisplay";
import MenuDisplay from "@/components/MenuDisplay/MenuDisplay";
import Title from "@/components/Title/Title";
import MenuSection from "@/components/MenuSection/MenuSection";
import SectionsContainer from "@/components/SectionsContainer/SectionsContainer";
import { DisplayProvider } from "@/hooks/BackGroundDisplayContext";
import ClipboarButton from "@/components/ClipboardButton/ClipboarButton";
import ClipBoardContainer from "@/components/ClipBoardContainer/ClipBoardContainer";

export default function Home() {
  const menuSections = ["Style", "Direction", "Colors", "Output format"];

  return (
    <>
      <Head>
        <title>CSS-Gradient-Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DisplayProvider>
        <main>
          <MenuDisplay>
            <Title />
            <SectionsContainer>
              {menuSections.map((section, index) => (
                <MenuSection key={index} type={section} />
              ))}
              <ClipBoardContainer>
                <ClipboarButton content="Get CSS" />
                <ClipboarButton content="Get Share Link" />
              </ClipBoardContainer>
            </SectionsContainer>
          </MenuDisplay>
          <BackgroundDisplay />
        </main>
      </DisplayProvider>
    </>
  );
}

/* <path d="M4.54.177a.692.692 0 0 1 .92 0l4.283 3.747a.776.776 0 0 1 .091 1.056.691.691 0 0 1-1.006.096L5.714 2.351v8.899c0 .414-.32.75-.714.75-.394 0-.714-.336-.714-.75V2.351L1.172 5.076A.691.691 0 0 1 .166 4.98a.776.776 0 0 1 .091-1.056L4.539.177z"></path>*/
